[3pt] PR: Enhancements to code to allow for evaluation at AHPS sites and generation of categorical FIM
NOAA-OWP/cahaba pull request #267
Opened 2021-02-19 18:55 UTC by BradfordBates-NOAA

Enhancements to code to allow for evaluation at AHPS sites and generation of categorical FIM. Evaluations at AHPS sites (NWS and USGS) are now possible.

This enhancement relies on a new directory structure in the `test_cases` directory. After this is merged into `dev` it will be necessary to update the test_cases directory with the new structure. `synthesize_test_cases.py` also produces a "master" CSV of metrics from all versions that allows for easy queries and plotting.

This PR addresses #258 and #259.

## Additions

- `generate_categorical_fim.py`

## Removals

- `auto_ble_eval`
- The code block that is responsible for printing the colored metrics to screen has now been commented out because of the new scale of evaluations.

## Changes

- `synthesize_test_cases.py`
- `run_test_case.py`
- `shared_functions.py`
- `shared_variables.py`
- `cache_metrics.py`

## Testing

1. Run `synthesize_test_cases.py` in DEV and PREV mode (-c)
2. Run `generate_categorical_fim.py`

Please confirm that these scripts run without error. The help (-h) ought to be fairly good for these.

2021-02-19 23:05 UTC, BrianAvant-NOAA requested changes
Do you want to remove ble_autoeval.sh from the repo?

2021-02-22 14:47 UTC, BradfordBates-NOAA commented
I removed `ble_autoeval.sh` and also removed `all_ble_stats_comparison.py`

2021-02-22 14:49 UTC, BrianAvant-NOAA approved these changes

2021-02-22 15:00 UTC, BrianAvant-NOAA approved these changes

2021-02-22 15:22 UTC, merged